version: '2'

services:
  Node-RED:
    image: nodered/node-red:latest-minimal
    hostname: Node-RED
    restart: always
    ports:
        - ${PORT}:1880
    networks:
        vlan2:
            ipv4_address: ${IP}       

networks:
    vlan2:
        ipam:
            driver: ${NETWORK}
            config:
                - subnet:  192.168.2.0/16
                - gateway: 192.168.2.1
                - ip-range: 192.168.0.128/25