version: '2'

services:
  Node-RED:
    image: nodered/node-red:latest-minimal
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    restart: always 
    ports:
        - ${PORT}:1880
    networks:
        front:
            ipv4_address: ${IP}
    volumes:
        - ${CONTAINER_NAME}:/data

networks:
    front:
        external:
            name: ${NETWORK}
