version: '2'

services:
  Node-RED:
    image: nodered/node-red:latest-minimal
    hostname: Node-RED
    restart: always 
    ports:
        - ${PORT}:1880
    networks:
        front:
            ipv4_address: ${IP}
    volumes:
        - "Node-RED-${PORT}":/data

networks:
    front:
        external:
            name: ${NETWORK}
